api/urls.py
from django.urls import include, re_path

urlpatterns = [
    re_path(r"^v1/", include(("api.v1.urls", "api"), namespace="v1")),
    re_path(r"", include(("api.v1.urls", "api"), namespace="last")),
]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

from scan.views.accounts import AccountsListView, AddressDetailView
from scan.views.assets import (
    AssetDetailView,
    AssetListView,
    AssetTradesListView,
    AssetTransfersListView,
)
from scan.views.ats import AtDetailView, AtListView
from scan.views.blocks import BlockDetailView, BlockListView
from scan.views.index import index
from scan.views.marketplace import (
    MarketPlaceDetailView,
    MarketPlaceListView,
    MarketPlacePurchasesListView,
)
from scan.views.multiout import MultiOutListView
from scan.views.peers import (
    PeerMonitorDetailView,
    PeerMonitorListView,
    peers_charts_view,
)
from scan.views.pending_transactions import pending_transactions
from scan.views.search import search_view
from scan.views.transactions import TxDetailView, TxListView

urlpatterns = [
    path("", index, name="index"),
    path("blocks/", BlockListView.as_view(), name="blocks"),
    path("block/<str:height>", BlockDetailView.as_view(), name="block-detail"),
    path("mos/", MultiOutListView.as_view(), name="mos"),
    path("txsPending/", pending_transactions, name="txs-pending"),
    path("txs/", TxListView.as_view(), name="txs"),
    path("tx/<str:id>", TxDetailView.as_view(), name="tx-detail"),
    path("accounts/", AccountsListView.as_view(), name="accounts"),
    path("address/<str:id>", AddressDetailView.as_view(), name="address-detail"),
    path("asset/trades", AssetTradesListView.as_view(), name="asset-trades"),
    path("asset/transfers", AssetTransfersListView.as_view(), name="asset-transfers"),
    path("assets/", AssetListView.as_view(), name="assets"),
    path("asset/<str:id>", AssetDetailView.as_view(), name="asset-detail"),
    path("mps/purchases", MarketPlacePurchasesListView.as_view(), name="mps-purchases"),
    path("mps/", MarketPlaceListView.as_view(), name="mps"),
    path("mp/<str:id>", MarketPlaceDetailView.as_view(), name="mp-detail"),
    path("ats/", AtListView.as_view(), name="ats"),
    path("at/<str:id>", AtDetailView.as_view(), name="at-detail"),
    path("search/", search_view, name="search"),
    path("peers/", PeerMonitorListView.as_view(), name="peers"),
    path("peers-charts/", peers_charts_view, name="peers-charts"),
    path("peer/<str:address>", PeerMonitorDetailView.as_view(), name="peer-detail"),
    path("admin/", admin.site.urls),
    path("api/", include(("api.urls", "api"), namespace="api")),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

java_wallet/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = True` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
from .fields import PositiveBigIntegerField, TimestampField


class Account(models.Model):
    db_id = models.BigAutoField(primary_key=True)
    id = PositiveBigIntegerField()
    creation_height = models.IntegerField()
    public_key = models.CharField(max_length=32, blank=True, null=True)
    key_height = models.IntegerField(blank=True, null=True)
    balance = PositiveBigIntegerField()
    unconfirmed_balance = PositiveBigIntegerField()
    forged_balance = PositiveBigIntegerField()
    name = models.CharField(max_length=100, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    height = models.IntegerField()
    latest = models.IntegerField()

    class Meta:
        managed = True
        db_table = 'account'
        unique_together = (('id', 'height'),)


class AccountAsset(models.Model):
    db_id = models.BigAutoField(primary_key=True)
    account_id = PositiveBigIntegerField()
    asset_id = PositiveBigIntegerField()
    quantity = PositiveBigIntegerField()
    unconfirmed_quantity = PositiveBigIntegerField()
    height = models.IntegerField()
    latest = models.IntegerField()

    class Meta:
        managed = True
        db_table = 'account_asset'
        unique_together = (('account_id', 'asset_id', 'height'),)


class Alias(models.Model):
    db_id = models.BigAutoField(primary_key=True)
    id = PositiveBigIntegerField()
    account_id = PositiveBigIntegerField()
    alias_name = models.CharField(max_length=100)
    alias_name_lower = models.CharField(max_length=100)
    alias_uri = models.TextField()
    timestamp = TimestampField()
    height = models.IntegerField()
    latest = models.IntegerField()

    class Meta:
        managed = True
        db_table = 'alias'
        unique_together = (('id', 'height'),)


class AliasOffer(models.Model):
    db_id = models.BigAutoField(primary_key=True)
    id = PositiveBigIntegerField()
    price = PositiveBigIntegerField()
    buyer_id = PositiveBigIntegerField(blank=True, null=True)
    height = models.IntegerField()
    latest = models.IntegerField()

    class Meta:
        managed = True
        db_table = 'alias_offer'
        unique_together = (('id', 'height'),)


class AskOrder(models.Model):
    db_id = models.BigAutoField(primary_key=True)
    id = PositiveBigIntegerField()
    account_id = PositiveBigIntegerField()
    asset_id = PositiveBigIntegerField()
    price = PositiveBigIntegerField()
    quantity = PositiveBigIntegerField()
    creation_height = models.IntegerField()
    height = models.IntegerField()
    latest = models.IntegerField()

    class Meta:
        managed = True
        db_table = 'ask_order'
        unique_together = (('id', 'height'),)


class Asset(models.Model):
    db_id = models.BigAutoField(primary_key=True)
    id = PositiveBigIntegerField(unique=True)
    account_id = PositiveBigIntegerField()
    name = models.CharField(max_length=10)
    description = models.TextField(blank=True, null=True)
    quantity = PositiveBigIntegerField()
    decimals = models.IntegerField()
    height = models.IntegerField()

    class Meta:
        managed = True
        db_table = 'asset'


class AssetTransfer(models.Model):
    db_id = models.BigAutoField(primary_key=True)
    id = PositiveBigIntegerField(unique=True)
    asset_id = PositiveBigIntegerField()
    sender_id = PositiveBigIntegerField()
    recipient_id = PositiveBigIntegerField()
    quantity = PositiveBigIntegerField()
    timestamp = TimestampField()
    height = models.IntegerField()

    class Meta:
        managed = True
        db_table = 'asset_transfer'


class At(models.Model):
    db_id = models.BigAutoField(primary_key=True)
    id = PositiveBigIntegerField()
    creator_id = PositiveBigIntegerField()
    name = models.CharField(max_length=30, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    version = models.SmallIntegerField()
    csize = models.IntegerField()
    dsize = models.IntegerField()
    c_user_stack_bytes = models.IntegerField()
    c_call_stack_bytes = models.IntegerField()
    creation_height = models.IntegerField()
    ap_code = models.TextField()
    height = models.IntegerField()
    latest = models.IntegerField()

    class Meta:
        managed = True
        db_table = 'at'
        unique_together = (('id', 'height'),)


class AtState(models.Model):
    db_id = models.BigAutoField(primary_key=True)
    at_id = PositiveBigIntegerField()
    state = models.TextField()
    prev_height = models.IntegerField()
    next_height = models.IntegerField()
    sleep_between = models.IntegerField()
    prev_balance = PositiveBigIntegerField()
    freeze_when_same_balance = models.IntegerField()
    min_activate_amount = PositiveBigIntegerField()
    height = models.IntegerField()
    latest = models.IntegerField()

    class Meta:
        managed = True
        db_table = 'at_state'
        unique_together = (('at_id', 'height'),)


class BidOrder(models.Model):
    db_id = models.BigAutoField(primary_key=True)
    id = PositiveBigIntegerField()
    account_id = PositiveBigIntegerField()
    asset_id = PositiveBigIntegerField()
    price = PositiveBigIntegerField()
    quantity = PositiveBigIntegerField()
    creation_height = models.IntegerField()
    height = models.IntegerField()
    latest = models.IntegerField()

    class Meta:
        managed = True
        db_table = 'bid_order'
        unique_together = (('id', 'height'),)


class Block(models.Model):
    db_id = models.BigAutoField(primary_key=True)
    id = PositiveBigIntegerField(unique=True)
    version = models.IntegerField()
    timestamp = TimestampField(unique=True)
    previous_block = models.ForeignKey('self', models.DO_NOTHING, blank=True, null=True, related_name='previous_block_r', to_field='id')
    total_amount = PositiveBigIntegerField()
    total_fee = PositiveBigIntegerField()
    payload_length = models.IntegerField()
    generator_public_key = models.CharField(max_length=32)
    previous_block_hash = models.CharField(max_length=32, blank=True, null=True)
    cumulative_difficulty = models.TextField()
    base_target = PositiveBigIntegerField()
    next_block = models.ForeignKey('self', models.DO_NOTHING, blank=True, null=True, related_name='next_block_r', to_field='id')
    height = models.IntegerField(unique=True)
    generation_signature = models.BinaryField(max_length=64)
    block_signature = models.CharField(max_length=64)
    payload_hash = models.CharField(max_length=32)
    generator_id = PositiveBigIntegerField()
    nonce = PositiveBigIntegerField()
    ats = models.TextField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'block'


class Escrow(models.Model):
    db_id = models.BigAutoField(primary_key=True)
    id = PositiveBigIntegerField()
    sender_id = PositiveBigIntegerField()
    recipient_id = PositiveBigIntegerField()
    amount = PositiveBigIntegerField()
    required_signers = models.IntegerField(blank=True, null=True)
    deadline = models.IntegerField()
    deadline_action = models.IntegerField()
    height = models.IntegerField()
    latest = models.IntegerField()

    class Meta:
        managed = True
        db_table = 'escrow'
        unique_together = (('id', 'height'),)


class EscrowDecision(models.Model):
    db_id = models.BigAutoField(primary_key=True)
    escrow_id = PositiveBigIntegerField()
    account_id = PositiveBigIntegerField()
    decision = models.IntegerField()
    height = models.IntegerField()
    latest = models.IntegerField()

    class Meta:
        managed = True
        db_table = 'escrow_decision'
        unique_together = (('escrow_id', 'account_id', 'height'),)


class Goods(models.Model):
    db_id = models.BigAutoField(primary_key=True)
    id = PositiveBigIntegerField()
    seller_id = PositiveBigIntegerField()
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)
    tags = models.CharField(max_length=100, blank=True, null=True)
    timestamp = TimestampField()
    quantity = models.IntegerField()
    price = PositiveBigIntegerField()
    delisted = models.IntegerField()
    height = models.IntegerField()
    latest = models.IntegerField()

    class Meta:
        managed = True
        db_table = 'goods'
        unique_together = (('id', 'height'),)


class Peer(models.Model):
    address = models.CharField(primary_key=True, max_length=100)

    class Meta:
        managed = True
        db_table = 'peer'


class Purchase(models.Model):
    db_id = models.BigAutoField(primary_key=True)
    id = PositiveBigIntegerField()
    buyer_id = PositiveBigIntegerField()
    goods_id = PositiveBigIntegerField()
    seller_id = PositiveBigIntegerField()
    quantity = models.IntegerField()
    price = PositiveBigIntegerField()
    deadline = models.IntegerField()
    note = models.TextField(blank=True, null=True)
    nonce = models.CharField(max_length=32, blank=True, null=True)
    timestamp = TimestampField()
    pending = models.IntegerField()
    goods = models.TextField(blank=True, null=True)
    goods_nonce = models.CharField(max_length=32, blank=True, null=True)
    refund_note = models.TextField(blank=True, null=True)
    refund_nonce = models.CharField(max_length=32, blank=True, null=True)
    has_feedback_notes = models.IntegerField()
    has_public_feedbacks = models.IntegerField()
    discount = PositiveBigIntegerField()
    refund = PositiveBigIntegerField()

scan/views/assets.py
from django.db.models import Q
from django.http import Http404
from django.views.generic import ListView

from java_wallet.models import Asset, AssetTransfer, Trade
from scan.caching_paginator import CachingPaginator
from scan.helpers.queries import get_account_name, get_asset_details
from scan.views.base import IntSlugDetailView
from scan.views.filters.assets import AssetTransferFilter, TradeFilter


def fill_data_asset_transfer(transfer):
    transfer.name, transfer.decimals, transfer.total_quantity = get_asset_details(
        transfer.asset_id
    )
    transfer.sender_name = get_account_name(transfer.sender_id)
    transfer.recipient_name = get_account_name(transfer.recipient_id)


def fill_data_asset_trade(trade):
    trade.name, trade.decimals, trade.total_quantity = get_asset_details(trade.asset_id)
    trade.buyer_name = get_account_name(trade.buyer_id)
    trade.seller_name = get_account_name(trade.seller_id)


class AssetListView(ListView):
    model = Asset
    queryset = Asset.objects.using("java_wallet").all()
    template_name = "assets/list.html"
    context_object_name = "assets"
    paginator_class = CachingPaginator
    paginate_by = 25
    ordering = "-height"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        obj = context[self.context_object_name]
        for t in obj:
            t.account_name = get_account_name(t.account_id)

        return context


class AssetTradesListView(ListView):
    model = Trade
    queryset = Trade.objects.using("java_wallet").all()
    template_name = "assets/trades.html"
    context_object_name = "assets_trades"
    paginator_class = CachingPaginator
    paginate_by = 25
    ordering = "-height"
    filter_set = None

    def get_queryset(self):
        self.filter_set = TradeFilter(self.request.GET, queryset=super().get_queryset())
        if self.filter_set.is_valid() and self.filter_set.data:
            qs = self.filter_set.qs[:100000]
        else:
            raise Http404()

        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["assets_trades_cnt"] = self.filter_set.qs.count()
        obj = context[self.context_object_name]
        for trade in obj:
            fill_data_asset_trade(trade)

        return context


class AssetTransfersListView(ListView):
    model = AssetTransfer
    queryset = AssetTransfer.objects.using("java_wallet").all()
    template_name = "assets/transfers.html"
    context_object_name = "assets_transfers"
    paginator_class = CachingPaginator
    paginate_by = 25
    ordering = "-height"
    filter_set = None

    def get_queryset(self):
        self.filter_set = AssetTransferFilter(
            self.request.GET, queryset=super().get_queryset()
        )
        if self.filter_set.is_valid() and self.filter_set.data:
            qs = self.filter_set.qs[:100000]
        else:
            raise Http404()

        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["assets_transfers_cnt"] = self.filter_set.qs.count()
        obj = context[self.context_object_name]
        for transfer in obj:
            fill_data_asset_transfer(transfer)

        return context


class AssetDetailView(IntSlugDetailView):
    model = Asset
    queryset = Asset.objects.using("java_wallet").all()
    template_name = "assets/detail.html"
    context_object_name = "asset"
    slug_field = "id"
    slug_url_kwarg = "id"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        obj = context[self.context_object_name]
        obj.account_name = get_account_name(obj.account_id)

        # assets transfer

        assets_transfers = (
            AssetTransfer.objects.using("java_wallet")
            .using("java_wallet")
            .filter(asset_id=obj.id)
            .order_by("-height")[:15]
        )

        for transfer in assets_transfers:
            fill_data_asset_transfer(transfer)

        context["assets_transfers"] = assets_transfers
        context["assets_transfers_cnt"] = (
            AssetTransfer.objects.using("java_wallet").filter(asset_id=obj.id).count()
        )

        # assets trades

        assets_trades = (
            Trade.objects.using("java_wallet")
            .using("java_wallet")
            .filter(asset_id=obj.id)
            .order_by("-height")[:15]
        )

        for trade in assets_trades:
            fill_data_asset_trade(trade)

        context["assets_trades"] = assets_trades
        context["assets_trades_cnt"] = (
            Trade.objects.using("java_wallet").filter(asset_id=obj.id).count()
        )
        return context

scan/views/pending_transactions.py
from django.shortcuts import render

from scan.caching_data.pending_txs import CachingPendingTxs


def pending_transactions(request):
    context = {"txs_pending": CachingPendingTxs().cached_data}
    return render(request, "txs_pending/list.html", context)

scan/templates/peers/charts.html
{% extends 'base.html' %}

{% load humanize %}

{% block title %} - Public Peers Charts{% endblock %}

{% block scripts %}
  <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
  <script type="text/javascript">
    google.charts.load('current', {
      'packages':['geochart'],
      // Note: you will need to get a mapsApiKey for your project.
      // See: https://developers.google.com/chart/interactive/docs/basic_load_libs#load-settings
      'mapsApiKey': 'AIzaSyD-9tSrke72PouQMnMX-a7eZSW0jkFMBWY'
    });
    google.charts.setOnLoadCallback(drawRegionsMap);

    function drawRegionsMap() {
      var data = google.visualization.arrayToDataTable([
        ['Country', 'Peers'],
        {% for country in countries %}['{{ country.country_code }}', {{ country.cnt }}],{% endfor %}
      ]);

      var options = {};

      var chart = new google.visualization.GeoChart(document.getElementById('regions_div'));

      chart.draw(data, options);
    }
  </script>

  <script type="text/javascript">
    google.charts.load('current', {'packages':['corechart']});
    google.charts.setOnLoadCallback(drawChart);

    function drawChart() {

      var data = google.visualization.arrayToDataTable([
        ['Version', 'Count'],
        {% for version in versions %}['{{ version.version }}', {{ version.cnt }}],{% endfor %}
      ]);

      var options = {
        title: 'Versions (Online)'
      };

      var chart = new google.visualization.PieChart(document.getElementById('piechart-versions'));

      chart.draw(data, options);
    }
  </script>

  <script type="text/javascript">
    google.charts.load('current', {'packages':['corechart']});
    google.charts.setOnLoadCallback(drawChart);

    function drawChart() {

      var data = google.visualization.arrayToDataTable([
        ['Version', 'Count'],
        {% for state in states %}['{{ state.state }}', {{ state.cnt }}],{% endfor %}
      ]);

      var options = {
        title: 'All known peers (last 30 days)'
      };

      var chart = new google.visualization.PieChart(document.getElementById('piechart-states'));

      chart.draw(data, options);
    }
  </script>

  <script>
    setTimeout(function(){
       document.location.reload();
    }, 30000);
  </script>
{% endblock %}

{% block content %}

  <h5 class="p-2">Public Peers</h5>

  <div class="card-deck mb-3">
    <div class="card mb-4 shadow-sm">
      <div class="card-body">
        <p>Online now: {{ online_now }} <span class="small">(checked {{ last_check.modified_at|naturaltime }})</span></p>

        <div id="regions_div"></div>

        <div id="piechart-versions"></div>

        <div id="piechart-states"></div>

      </div>
    </div>
  </div>

{% endblock %}

scan/templates/peers/detail.html
{% extends 'base.html' %}

{% load humanize %}

{% block title %} - Peer {{ peer.announced_address }}{% endblock %}

{% block content %}

  <h5 class="p-2">Peer {{ peer.announced_address }}</h5>

  <div class="card-deck mb-3">
    <div class="card mb-4 shadow-sm">
      <div class="card-body">

        <div class="table-responsive">
          <table class="table small table-sm">
            <tbody>
            <tr>
              <th style="width: 160px;">State</th>
              <td>{{ peer.get_state_display }}</td>
            </tr>
            <tr>
              <th>Height</th>
              <td>{{ peer.height }}</td>
            </tr>
            <tr>
              <th>Availability</th>
              <td>{{ peer.availability|floatformat:2 }}%</td>
            </tr>
            <tr>
              <th>Version</th>
              <td>{{ peer.version }}</td>
            </tr>
            <tr>
              <th>Country</th>
              <td>{{ peer.country_code }}</td>
            </tr>
            <tr>
              <th>Application</th>
              <td>{{ peer.application }}</td>
            </tr>
            <tr>
              <th>Platform</th>
              <td>{{ peer.platform }}</td>
            </tr>
            <tr>
              <th>Found</th>
              <td>{{ peer.created_at }}</td>
            </tr>
            <tr>
              <th>Last Online</th>
              <td>{{ peer.last_online_at }}</td>
            </tr>
            <tr>
              <th>Checked</th>
              <td>{{ peer.modified_at|naturaltime }}</td>
            </tr>
            </tbody>
          </table>
        </div>

      </div>
    </div>
  </div>

{% endblock %}

scan/templates/peers/list.html
{% extends 'base.html' %}

{% load humanize %}

{% block title %} - Public Peers List{% endblock %}

{% block content %}

  <h5 class="p-2">Public Peers</h5>

  <div class="card-deck mb-3">
    <div class="card mb-4 shadow-sm">
      <div class="card-body">
        <div class="d-flex flex-column flex-md-row align-items-center">
          <small class="my-0 mr-md-auto text-muted">
              A total of {{ paginator.count|intcomma }} peers found
          </small>
          {% include "paginator.html" %}
        </div>

        <div class="table-responsive">
          <table class="table table-hover small table-sm">
            <thead>
            <tr>
              <th scope="col">Announced Address</th>
              <th scope="col">State</th>
              <th scope="col">Availability</th>
              <th scope="col">Height</th>
              <th scope="col">Version</th>
              <th scope="col">Country</th>
            </tr>
            </thead>
            <tbody>
            {% for peer in peers %}
              <tr>
                <td><a href="{% url 'peer-detail' peer.announced_address %}">{{ peer.announced_address }}</a></td>
                <td>{{ peer.get_state_display }}</td>
                <td>{{ peer.availability|floatformat:2 }}%</td>
                <td>{{ peer.height }}</td>
                <td>{{ peer.version }}</td>
                <td>{{ peer.country_code }}</td>
              </tr>
            {% endfor %}
            </tbody>
          </table>
        </div>

        {% include "paginator.html" %}

      </div>
    </div>
  </div>

{% endblock %}